"""Add reminder_date to Task

Revision ID: 340aeb2d3c87
Revises: ecb661d82842
Create Date: 2024-08-21 20:06:02.700272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340aeb2d3c87'
down_revision = 'ecb661d82842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('reminder_date')

    # ### end Alembic commands ###
