"""Add Task model

Revision ID: 63617df4cd83
Revises: 7c7f128fb45d
Create Date: 2024-08-19 21:32:39.564940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63617df4cd83'
down_revision = '7c7f128fb45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
