"""Add user_id to Customer

Revision ID: 823c4e4486e8
Revises: 342be86510ea
Create Date: 2024-08-27 14:45:33.546739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823c4e4486e8'
down_revision = '342be86510ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_customer_user',  # Додайте ім'я для обмеження
            'user', 
            ['user_id'], 
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customer_user', type_='foreignkey')  # Використайте ім'я обмеження тут
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
