"""Додані нові поля до Customer

Revision ID: e901e97bb836
Revises: 31e8a2b21c04
Create Date: 2024-08-24 23:39:38.285084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e901e97bb836'
down_revision = '31e8a2b21c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('login', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('podstawa', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('case_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('condition_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deposit', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('documents', sa.String(length=100), nullable=True))
        batch_op.drop_column('profile_picture')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('two_factor_secret',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('two_factor_secret',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('documents')
        batch_op.drop_column('paid')
        batch_op.drop_column('deposit')
        batch_op.drop_column('condition_type')
        batch_op.drop_column('contact')
        batch_op.drop_column('case_number')
        batch_op.drop_column('podstawa')
        batch_op.drop_column('login')
        batch_op.drop_column('password')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
